---

- name: apt install
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - uuid-runtime
    - rsync
    - daemontools # supervise
  sudo_user: root

########################################################################
#                    INSTALL GITHUB KEY AND CHECKOUT                   #
########################################################################

- name: mkdir ~/.ssh
  file: path={{ home }}/.ssh state=directory
- name: check for the smarthome-services id_rsa
  stat: path={{ home }}/.ssh/id_rsa
  register: p
- name: upload the smarthome-services id_rsa
  copy: src=smarthome-services dest={{ home }}/.ssh/id_rsa mode=600
  when: p.stat.isreg is not defined or p.stat.isreg == false

- name: cache the github.com host key
  shell: creates="{{ home }}/.ssh/.cached-host-key-github.com"
      ssh-keyscan -t ecdsa,rsa,dsa github.com >> ~/.ssh/known_hosts;
      touch {{ home }}/.ssh/.cached-host-key-github.com

- name: checkout the hub repo
  git: dest={{ app }} repo={{ hub_repo }} depth=1 version={{ hub_rev }}
- name: checkout the config repo
  git: dest={{ config }} repo={{ config_repo }} depth=1 version={{ config_rev }}
- name: checkout the blobs repo
  git: dest={{ blobs }} repo={{ blobs_repo }} depth=1 version={{ blobs_rev }}
- name: checkout the drivers repo
  git: dest={{ drivers }} repo={{ drivers_repo }} depth=1 version={{ drivers_rev }}
- name: checkout the tunneler repo
  git: dest={{ tunneler }} repo={{ tunneler_repo }} depth=1 version={{ tunneler_rev }}


########################################################################
#                    DEPENDENCIES INSTALLATION                         #
########################################################################

## (apt moved to the top)

- name: get the pip installer
  get_url: url=https://raw.github.com/pypa/pip/master/contrib/get-pip.py
      dest={{ home }}/get-pip.py owner=root group=root mode=0755
  sudo_user: root
- name: install pip
  command: python {{ home }}/get-pip.py
      creates=/usr/local/bin/pip
  sudo_user: root
- name: install virtualenv
  pip: name=virtualenv version=1.11.4
      extra_args="--no-index --use-wheel --find-links={{ blobs }}/wheelhouse"
  sudo_user: root

- name: install the google-dns tool
  copy: src=google-dns dest=/usr/local/bin/google-dns
      owner=root group=root mode=0755
  sudo_user: root

- name: install usbreset /1
  command: cp {{ blobs }}/usbreset-{{ ansible_machine }} /usr/local/bin/usbreset
      creates=/usr/local/bin/usbreset
  # Note: this will not update usbreset if changed
  sudo_user: root
- name: install usbreset /2
  file: path=/usr/local/bin/usbreset owner=root group=root mode=0755
  sudo_user: root

- name: create the virtualenv and install requirements.txt
  pip: virtualenv={{ home }}/ENV/ requirements={{ app }}/requirements.txt
      extra_args="--no-index --use-wheel --find-links={{ blobs }}/wheelhouse"


########################################################################
#            GENERATE/GET/INSTALL THE HUB-ID AND THE CLASSES           #
########################################################################

- name: generate hub unique UUID if not existing
  shell: creates={{ home }}/.hub-id
      uuidgen > {{ home }}/.hub-id
  when: user_hub_id is not defined

- name: check the user_hub_id/1
  shell: executable=/bin/bash [[ {{ user_hub_id }} =~ ^[a-z0-9-]+$ ]]
  when: user_hub_id is defined
  register: result
  ignore_errors: True
- name: check the user_hub_id/2
  fail: msg="invalid characters in the user_hub_id"
  when: result|failed

- name: install the user_hub_id
  copy: content={{ user_hub_id }} dest={{ home }}/.hub-id
  when: user_hub_id is defined

# - name: get the hub unique UUID
#   command: "cat {{ home }}/.hub-id"
#   register: hub_id
# - debug: >
#     msg="hub-id: {{ hub_id.stdout }}"

- name: ensure .hub-classes exists
  file: path={{ home }}/.hub-classes state=touch
- name: install the hub classes
  copy: content={{ hub_classes }} dest={{ home }}/.hub-classes
  when: hub_classes is defined


########################################################################
#                                IMPORTS                               #
########################################################################

- include: armv6l.yml
  when: ansible_machine=="armv6l"
- include: x86_64.yml
  when: ansible_machine=="x86_64"

# Run upgrade migrations tasks
- include: upgrade.yml

- include: drivers.yml


########################################################################
#                               TUNNELER                               #
########################################################################

- name: extract tunneler host
  shell: "{{ app }}/config.py | jq --raw-output .ssh_bridge_host"
  register: ssh_bridge_host
- name: cache the remote host key
  shell: creates="{{ home }}/.ssh/.cached-host-key-{{ ssh_bridge_host.stdout.strip() }}"
      ssh-keyscan -t ecdsa,rsa,dsa {{ ssh_bridge_host.stdout.strip() }} >> ~/.ssh/known_hosts;
      touch {{ home }}/.ssh/.cached-host-key-{{ ssh_bridge_host.stdout.strip() }}

- name: install the tunneler init script
  template: src=tunneler dest=/etc/init.d/tunneler
      owner=root group=root mode=0755
  sudo_user: root
- name: enable tunneler
  service: name=tunneler enabled=yes state=started
  sudo_user: root

- name: install the ssh config
  copy: src=ssh_config dest={{ home }}/.ssh/config

########################################################################
#                                 MISC                                 #
########################################################################

- name: disable rsyslogd
  service: name=rsyslog state=stopped enabled=no
  sudo_user: root

# Install the smarthome-remote-key
- name: check for the smarthome-remote-key
  stat: path={{ home }}/smarthome-remote-key
  register: p
- name: upload the smarthome-remote-key
  copy: src=smarthome-remote-key dest={{ home }}/smarthome-remote-key mode=600
  when: p.stat.isreg is not defined or p.stat.isreg == false

# Cache the remotehost SSH host key
- name: extract remote host
  shell: "{{ app }}/config.py | jq --raw-output .remotehost"
  register: remotehost
- name: cache the remote host key
  shell: creates="{{ home }}/.ssh/.cached-host-key-{{ remotehost.stdout.strip() }}"
      ssh-keyscan -t ecdsa,rsa,dsa {{ remotehost.stdout.strip() }} >> ~/.ssh/known_hosts;
      touch {{ home }}/.ssh/.cached-host-key-{{ remotehost.stdout.strip() }}

# Create folders
- name: extract the folders that have to be created
  shell: >
      {{ app }}/config.py | jq --raw-output '[.logs_path+(.logging_modules|.[]), .logs_path+(.loaded_drivers|.[])+"-driver", .logs_path, .data_path]|.[]'
  register: folders
- name: mkdir
  file: path={{ item }} state=directory
  with_items: folders.stdout_lines

# Upload a script to ensure that the folders exist on boot
- name: upload /etc/init.d/mkdirs
  template: src=mkdirs dest=/etc/init.d/mkdirs
      owner=root group=root mode=0755
  sudo_user: root
- name: enable /etc/init.d/mkdirs
  service: name=mkdirs enabled=yes
  sudo_user: root

# Setup sudoers file
- name: setup sudo
  template: src=sudoers dest=/etc/sudoers.d/smarthome validate='visudo -cf %s'
      owner=root group=root
  sudo_user: root

# Setup cronjobs
- name: create cron entries
  cron: name="run '{{ item }}'"
      job=". /etc/profile; . $HOME/.profile; cd '{{ app }}'; '{{ app }}/{{ item }}'"
  with_items:
    - smarthome-hub-runner.sh
    - smarthome-hub-watchdog.sh
