---
home: "/home/{{ ansible_user_id }}"

deploy: "{{ home }}/smarthome-deployment"
blobs: "{{ home }}/smarthome-deployment-blobs"

logfile: "{{ home }}/ansible-pull.log" # TODO
synced_logfile: "/home/smarthome/smarthome/logs/pull/ansible-pull.$(date --utc +%Y-%m-%d-%H-%M).log"

deploy_repo: "git@github.com:smart-home/smarthome-deployment.git"
deploy_rev: "master"
blobs_repo: "git@github.com:smart-home/smarthome-deployment-blobs.git"
blobs_rev: "master"

pulling: False # Defaults to False, set to True by local.yml
