#!/bin/bash

### BEGIN INIT INFO
# Provides:        monitor_alerting
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Run the monitor alerting server
### END INIT INFO

case $1 in
    start)
        sudo -u admin supervise {{ monitor }}/alerting &
        ;;
    *)
        echo "Usage: $0 start"
        exit 1
        ;;
esac
