#! /bin/bash

git_pull() {
    local folder="$1"

    cd "$folder"
    git pull
}

main() {
    local folders=('{{ code }}' '{{ config }}' '{{ blobs }}')
    local f

    for f in "${folders[@]}"
    do
        git_pull "$f"
    done

    pkill --full "http.py"
    pkill --full "alerting.py"
}

main
