#!/usr/bin/env python2.7

import json
import subprocess
import os.path

CONFIG_PATH = os.path.expanduser('~/config.json')
with open(CONFIG_PATH) as f:
    config = json.load(f)

with open(os.path.expanduser('~/.node-id')) as f:
    UUID = f.read().strip()

ssh_host = "piloteur@%s" % config['ssh_bridge_host']

p = subprocess.Popen(['ssh', ssh_host], stdout=subprocess.PIPE, stdin=subprocess.PIPE)
port = p.communicate(input=UUID)[0].strip()

subprocess.check_call(['ssh', '-N', '-R', port+":127.0.0.1:22", ssh_host])
