- name: wait for instance to listen on port:22
  local_action: wait_for
    state=started
    host={{ inventory_hostname }}
    port=22
  sudo: no

- name: cache the node host key
  local_action: shell ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
  sudo: no

- user: name={{ initial_user }} password=!

- user: name=admin password=! shell=/bin/bash
- name: add piloteur-admin to authorized_key
  authorized_key: user=admin
    key="{{ lookup('file', 'piloteur-admin.pub') }}"
- name: setup sudo
  copy: content="admin ALL=(ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/piloteur
    validate='visudo -cf %s' owner=root group=root

- user: name=piloteur

- name: install python-apt // workaround Ansible 1.5.3 bug #6530
  shell: dpkg -s python-apt || apt-get update && apt-get install -y python-apt
