---

- name: apt install
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
  sudo_user: root

########################################################################
#                    INSTALL GITHUB KEY AND CHECKOUT                   #
########################################################################

- name: mkdir ~/.ssh
  file: path={{ home }}/.ssh state=directory
- name: check for the piloteur-devices id_rsa
  stat: path={{ home }}/.ssh/id_rsa
  register: p
- name: upload the piloteur-devices id_rsa
  copy: src=piloteur-devices dest={{ home }}/.ssh/id_rsa mode=600
  when: p.stat.isreg is not defined or p.stat.isreg == false

- name: cache the github.com host key
  shell: creates="{{ home }}/.ssh/.cached-host-key-github.com"
      ssh-keyscan -t ecdsa,rsa,dsa github.com >> ~/.ssh/known_hosts;
      touch {{ home }}/.ssh/.cached-host-key-github.com

- name: checkout the code repo
  git: dest={{ code }} repo={{ code_repo }} depth=1 version={{ code_rev }}

########################################################################
#                    DEPENDENCIES INSTALLATION                         #
########################################################################

- name: x86_64 | install jq
  get_url: url=https://github.com/stedolan/jq/raw/gh-pages/download/linux64/jq
      dest=/usr/local/bin/jq owner=root group=root mode=0755
  sudo_user: root

########################################################################
#                        MAIN BRIDGE DEPENDENCIES                      #
########################################################################

- name: mkdir ~/ssh_ports/
  file: path={{ home }}/ssh_ports/ state=directory

- name: add the ssh piloteur-devices key and command
  authorized_key: user={{ ansible_user_id }}
    key_options='command="{{ bridge }}/shell.py"'
    key="{{ lookup('file', 'piloteur-devices.pub') }}"

- name: workaround ansible/ansible#6881
  lineinfile: dest=/etc/ssh/sshd_config line=" "
  sudo_user: root
- name: add ClientAliveInterval to sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="^ClientAliveInterval "
    line="ClientAliveInterval 15"
  sudo_user: root
- name: add ClientAliveCountMax to sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="^ClientAliveCountMax "
    line="ClientAliveCountMax 4"
  sudo_user: root

- name: create cron entry
  cron: name="run ports cleanup"
      job=". /etc/profile; . $HOME/.profile; cd '{{ bridge }}'; '{{ bridge }}/cron.py'"
