- hosts: all
  gather_facts: False
  remote_user: admin
  sudo: yes
  tasks:
    - user: name=piloteur
    - name: add piloteur-admin to authorized_key
      authorized_key: user=admin
        key="{{ lookup('file', '../keys/piloteur-admin.pub') }}"
    - user: name=admin password=!

    - name: install python-apt // workaround Ansible 1.5.3 bug #6530
      shell: dpkg -s python-apt || apt-get update && apt-get install -y python-apt

- hosts: all
  gather_facts: True
  remote_user: admin
  sudo_user: piloteur
  sudo: yes
  roles:
    - bridge
