# Requires Ansible >= 1.5.3 due to bug #6430

- hosts: localhost
  gather_facts: True
  vars_files:
    - ../../repo_overrides.yml
  vars:
    pulling: True
  roles:
    - endpoint-pull

- hosts: localhost
  gather_facts: True
  sudo_user: smarthome
  sudo: yes
  vars_files:
    - ../../repo_overrides.yml
  roles:
    - endpoint
