- hosts: all
  gather_facts: False
  remote_user: "{{ initial_user }}"
  sudo: yes
  roles:
    - piloteur

- hosts: all
  gather_facts: True
  remote_user: admin
  sudo_user: piloteur
  sudo: yes
  vars_files:
    - repo_definitions.yml
  roles:
    - endpoint

- hosts: all
  gather_facts: True
  remote_user: admin
  vars_files:
    - repo_definitions.yml
  roles:
    - endpoint-pull
