- hosts: raspberrypi
  gather_facts: False
  remote_user: pi
  sudo: yes
  tasks:
    - user: name=pi password=!

    - user: name=piloteur

    - user: name=admin groups=sudo password=!
    - name: add smarthome-services to authorized_key
      authorized_key: user=admin
        key="{{ lookup('file', '../keys/smarthome-services.pub') }}"

    - name: install python-apt // workaround Ansible 1.5.3 bug #6530
      shell: dpkg -s python-apt || apt-get update && apt-get install -y python-apt

- hosts: raspberrypi
  gather_facts: True
  remote_user: admin
  sudo_user: piloteur
  sudo: yes
  vars_files:
    - repo_overrides.yml
  roles:
    - endpoint

- hosts: raspberrypi
  gather_facts: True
  remote_user: admin
  vars_files:
    - repo_overrides.yml
  roles:
    - endpoint-pull
