- hosts: all
  gather_facts: False
  remote_user: "{{ initial_user }}"
  sudo: yes
  roles:
    - piloteur

- hosts: all
  gather_facts: True
  remote_user: admin
  # TODO: segregate this into a different user
  vars_files:
    - repo_definitions.yml
  roles:
    - { role: unattended-upgrades, sudo: yes, email: bip@filippo.io }
    - monitor
