##########################
# Usage:
#
# ansible-playbook -i ec2.py monitor.yml
##########################

- hosts: tag_smarthome_monitor
  gather_facts: False
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: add smarthome-services to authorized_key
      authorized_key: user=ubuntu
        key="{{ lookup('file', 'keys/smarthome-services.pub') }}"
    - user: name=ubuntu password=!

    - name: install python-apt // workaround Ansible 1.5.3 bug #6530
      shell: dpkg -s python-apt || apt-get update && apt-get install -y python-apt

- hosts: tag_smarthome_monitor
  gather_facts: True
  remote_user: ubuntu
  # TODO: segregate this into a different user
  roles:
    - { role: unattended-upgrades, sudo: yes, email: bip@filippo.io }
    - monitor
