- hosts: raspberrypi
  gather_facts: False
  remote_user: pi
  sudo: yes
  tasks:
    - user: name=smarthome
    - name: add smarthome-services to authorized_key
      authorized_key: user=pi
        key="{{ lookup('file', 'keys/smarthome-services.pub') }}"
    - user: name=pi password=!

    - name: install python-apt // workaround Ansible 1.5.3 bug #6530
      shell: dpkg -s python-apt || apt-get update && apt-get install -y python-apt

- hosts: raspberrypi
  gather_facts: True
  remote_user: pi
  sudo_user: smarthome
  sudo: yes
  vars_files:
    - "{{ repo_overrides }}"
  roles:
    - hub

- hosts: raspberrypi
  gather_facts: True
  remote_user: pi
  vars_files:
    - "{{ repo_overrides }}"
  roles:
    - hub-pull
