- debug: 'msg="WARNING: You will need ansible-playbook 1.5.2 at least for this"'

- name: mkdir
  file: path={{ item }} state=directory mode=750
  with_items:
    - "{{ ansible_env.HOME }}/piloteur"
    - "{{ ansible_env.HOME }}/piloteur/data"
    - "{{ ansible_env.HOME }}/piloteur/logs"

- name: upload the ssh jail script
  copy: src=rsync_host.py dest={{ ansible_env.HOME }}/rsync_host.py mode=750

- name: add piloteur-devices to authorized_key
  authorized_key: user={{ ansible_user_id }}
    key_options='command="/usr/bin/python {{ ansible_env.HOME }}/rsync_host.py"'
    key="{{ lookup('file', '../keys/piloteur-devices.pub') }}"
