---
- name: mkdir ~/.ssh
  file: path={{ home }}/.ssh state=directory
- name: upload the piloteur-devices id_rsa
  copy: src=piloteur-devices dest={{ home }}/.ssh/id_rsa mode=600

- name: upload repo_definitions.yml
  copy: src=repo_definitions.yml dest={{ home }}/repo_definitions.yml
