#!/bin/bash

### BEGIN INIT INFO
# Provides:        bridge
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Run the SSH bridge client
### END INIT INFO

case $1 in
    start)
        sudo -u piloteur supervise {{ endpoint }}/bridge &
        ;;
    *)
        echo "Usage: $0 start"
        exit 1
        ;;
esac
